before:
  hooks:
    - go mod download
builds:
  - id: kubectl-tap
    main: ./cmd/kubectl-tap
    binary: kubectl-tap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - builds:
      - kubectl-tap
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE